# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA_project/xilinx/summerschool2022/DSP/prj/fir_vivado_prj/fir_vivado_prj.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
# IP: The module: 'design_1_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_project/xilinx/summerschool2022/DSP/prj/fir_vivado_prj/fir_vivado_prj.gen/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/FPGA_project/xilinx/summerschool2022/DSP/prj/fir_vivado_prj/fir_vivado_prj.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
# IP: The module: 'design_1_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_project/xilinx/summerschool2022/DSP/prj/fir_vivado_prj/fir_vivado_prj.gen/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
